export default [
  {"name":"Alabama","a2":"AL"},
  {"name":"Alaska","a2":"AK"},
  {"name":"Arizona","a2":"AZ"},
  {"name":"Arkansas","a2":"AR"},
  {"name":"California","a2":"CA"},
  {"name":"Colorado","a2":"CO"},
  {"name":"Connecticut","a2":"CT"},
  {"name":"Delaware","a2":"DE"},
  {"name":"District of Columbia","a2":"DC"},
  {"name":"Florida","a2":"FL"},
  {"name":"Georgia","a2":"GA"},
  {"name":"Hawaii","a2":"HI"},
  {"name":"Idaho","a2":"ID"},
  {"name":"Illinois","a2":"IL"},
  {"name":"Indiana","a2":"IN"},
  {"name":"Iowa","a2":"IA"},
  {"name":"Kansa","a2":"KS"},
  {"name":"Kentucky","a2":"KY"},
  {"name":"Lousiana","a2":"LA"},
  {"name":"Maine","a2":"ME"},
  {"name":"Maryland","a2":"MD"},
  {"name":"Massachusetts","a2":"MA"},
  {"name":"Michigan","a2":"MI"},
  {"name":"Minnesota","a2":"MN"},
  {"name":"Mississippi","a2":"MS"},
  {"name":"Missouri","a2":"MO"},
  {"name":"Montana","a2":"MT"},
  {"name":"Nebraska","a2":"NE"},
  {"name":"Nevada","a2":"NV"},
  {"name":"New Hampshire","a2":"NH"},
  {"name":"New Jersey","a2":"NJ"},
  {"name":"New Mexico","a2":"NM"},
  {"name":"New York","a2":"NY"},
  {"name":"North Carolina","a2":"NC"},
  {"name":"North Dakota","a2":"ND"},
  {"name":"Ohio","a2":"OH"},
  {"name":"Oklahoma","a2":"OK"},
  {"name":"Oregon","a2":"OR"},
  {"name":"Pennsylvania","a2":"PA"},
  {"name":"Rhode Island","a2":"RI"},
  {"name":"South Carolina","a2":"SC"},
  {"name":"South Dakota","a2":"SD"},
  {"name":"Tennessee","a2":"TN"},
  {"name":"Texas","a2":"TX"},
  {"name":"Utah","a2":"UT"},
  {"name":"Vermont","a2":"VT"},
  {"name":"Virginia","a2":"VA"},
  {"name":"Washington","a2":"WA"},
  {"name":"West Virginia","a2":"WV"},
  {"name":"Wisconsin","a2":"WI"},
  {"name":"Wyoming","a2":"WY"}
];